export enum ServiceOrderStatus {
  OPEN = 'OPEN',
  IN_PRODUCTION = 'IN_PRODUCTION',
  PARTIALLY_FINISHED = 'PARTIALLY_FINISHED',
  FINISHED = 'FINISHED',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELED'
}